--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#000000"
foreground="#ffffff"
cursor="#be6262"

-- Colors
color0="#191919"
color1="#eb3d51"
color2="#66b61a"
color3="#d98e1d"
color4="#23ffa8"
color5="#ff00da"
color6="#68a783"
color7="#eaeaea"
color8="#484848"
color9="#eb3d51"
color10="#66b61a"
color11="#d98e1d"
color12="#23ffa8"
color13="#ff00da"
color14="#68a783"
color15="#eaeaea"
