# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#073642'
foreground='#fdf6e3'
cursor='#dc322f'

# Colors
color0='#073642'
color1='#dc322f'
color2='#859900'
color3='#b58900'
color4='#268bd2'
color5='#d33682'
color6='#2aa198'
color7='#eee8d5'
color8='#6c7c80'
color9='#dc322f'
color10='#859900'
color11='#b58900'
color12='#268bd2'
color13='#d33682'
color14='#2aa198'
color15='#eee8d5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
