--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#073642"
foreground="#fdf6e3"
cursor="#dc322f"

-- Colors
color0="#073642"
color1="#dc322f"
color2="#859900"
color3="#b58900"
color4="#268bd2"
color5="#d33682"
color6="#2aa198"
color7="#eee8d5"
color8="#6c7c80"
color9="#dc322f"
color10="#859900"
color11="#b58900"
color12="#268bd2"
color13="#d33682"
color14="#2aa198"
color15="#eee8d5"
