# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#000000'
foreground='#ffffff'
cursor='#be6262'

# Colors
color0='#191919'
color1='#eb3d51'
color2='#66b61a'
color3='#d98e1d'
color4='#23ffa8'
color5='#ff00da'
color6='#68a783'
color7='#eaeaea'
color8='#484848'
color9='#eb3d51'
color10='#66b61a'
color11='#d98e1d'
color12='#23ffa8'
color13='#ff00da'
color14='#68a783'
color15='#eaeaea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
